services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: es_td_ngo_backend
    ports:
      - "8000:8000"
    environment:
      - DB_USER=gen_user
      - DB_PASS=#BeH)(rn;Cl}7a
      - DB_HOST=99f541abb57e364deed82c1d.twc1.net
      - DB_PORT=5432
      - DB_NAME=default_db
      - DB_SSLMODE=verify-full
      - DB_SSLCERT=/app/certs/root.crt
    volumes:
      - ./backend/certs:/app/certs:ro
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: es_td_ngo_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
